spring:
  cloud:
    gateway:
      mvc:
        routes:
          - id: mainapplication
            uri: lb://mainapplication
            predicates:
              - Path=/mainapplication/api/**
            filters:
              - RewritePath=/mainapplication/api/(?<segment>.*), /api/${segment}
              - name: CircuitBreaker
                args:
                  id: userCircuitBreaker
                  fallbackUri: forward:/fallback

    resilience4j:
      circuitbreaker:
        configs:
          default:
            registerHealthIndicator: true
            slidingWindowSize: 10
            failureRateThreshold: 50
            waitDurationInOpenState: 5000
        instances:
          userCircuitBreaker:
            baseConfig: default

server:
  port: 8085